version: "3.9"

services:        
    redis:
        image: redis:alpine
        container_name: redis
        ports: 
            - 6379:6379
        volumes:
            - redis:/data

    mongodb:
        image: mongo
        container_name: mongodb
        ports:
            - 27017:27017
    environment:
        MONGO_INITDB_ROOT_USERNAME: docker
        MONGO_INITDB_ROOT_PASSWORD: ed7fe13984614f6d9cca139f529ae1e0
        volumes:
            - /path/on/host/mongo-data:/data/db

volumes:
  redis:
    driver: local

  
